# Generated by Django 4.0.1 on 2022-05-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('numeroT', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
